//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreWithSlack.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScoreWithSlackEntities : DbContext
    {
        public ScoreWithSlackEntities()
            : base("name=ScoreWithSlackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<Season> Season { get; set; }
        public virtual DbSet<SlackTeam> SlackTeam { get; set; }
    }
}
