//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoreWithSlack.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreId { get; set; }
        public System.DateTime ScoreDate { get; set; }
        public int Value { get; set; }
        public int ScoreForProfileId { get; set; }
        public int ScoreFromProfileId { get; set; }
        public int SeasonId { get; set; }
        public string SlackTeamId { get; set; }
    
        public virtual Profile ScoreForProfile { get; set; }
        public virtual Profile ScoreFromProfile { get; set; }
        public virtual Season Season { get; set; }
        public virtual SlackTeam SlackTeam { get; set; }
    }
}
